### ISSUE TITLE
[Feature] Set Up GraphQL Codegen for Contentful Integration in Next.js 15 App Router

### ISSUE THREAD

**Issue by patgpt** [patgpt/kellygroup-next-saas#11]
### Feature Details

**Objective**:  
Implement a type-safe Contentful CMS integration using GraphQL Codegen to enable static generation of content in server components.

**Acceptance Criteria**:
- [x] GraphQL Codegen configured with Contentful Delivery API
- [x] Type-safe queries for server components
- [x] Static path generation support
- [x] Environment variable security
- [x] Watch mode for schema changes
- [x] Zero client bundle impact

**Implementation Steps**:

1. **Codegen Configuration** (`codegen.yml`)
```yaml
schema:
  - https://graphql.contentful.com/content/v1/spaces/${CONTENTFUL_SPACE_ID}:
      headers:
        Authorization: Bearer ${CONTENTFUL_DELIVERY_TOKEN}
documents: './app/**/*.graphql'
generates:
  ./app/__generated__/:
    preset: client
    plugins:
      - typescript
      - typescript-operations
    config:
      preResolveTypes: true
      enumsAsTypes: true
      defaultScalarType: unknown
```

2. **Required Dependencies**
```bash
bun add --dev @graphql-codegen/client-preset @graphql-codegen/typescript @graphql-codegen/typescript-operations
```

3. **Environment Setup** (`.env.local`)
```env
CONTENTFUL_SPACE_ID=fs5tsm2181s6
CONTENTFUL_DELIVERY_TOKEN=OXXaccudqnes4CyMM5DIsMZYnrzZbd_Znc-KcUswfjw
```

4. **Contentful Client Utility** (`lib/contentful.ts`)
```ts
import { getSdk } from '../app/__generated__';
import { GraphQLClient } from 'graphql-request';

export const contentfulClient = new GraphQLClient(
  `https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}`,
  { headers: { Authorization: `Bearer ${process.env.CONTENTFUL_DELIVERY_TOKEN}` } }
);

export const contentful = getSdk(contentfulClient);
```

5. **Scripts** (`package.json`)
```json
{
  "scripts": {
    "generate": "graphql-codegen --config codegen.yml",
    "generate:watch": "graphql-codegen --config codegen.yml --watch"
  }
}
```

6. **Example Page Implementation** (`app/[slug]/page.tsx`)
```tsx
import { contentful } from '@/lib/contentful';

export async function generateStaticParams() {
  const { data } = await contentful.GetAllSlugs();
  return data?.pageCollection?.items.map(({ slug }) => ({ slug })) || [];
}

export default async function Page({ params }: { params: { slug: string } }) {
  const { data } = await contentful.GetPageBySlug({ slug: params.slug });
  // Page implementation
}
```

**Additional Notes**:
- Add `__generated__` and `.env.local` to `.gitignore`
- Consider adding `// @ts-nocheck` to generated files if needed
- Preview mode implementation should be a separate follow-up task
- All Contentful types will be automatically available via codegen
- Server components should use direct Contentful client (no React Query needed)

**Labels**:  
`enhancement` `documentation` `dependencies`

**Blockers**:  
None identified - Contentful credentials already available in environment

 

### Priority

Critical (Must have)
